// Code generated by scripts/gen-contract.js from contract/contract.json; DO NOT EDIT.
// Single source of truth: ai-native-cli-spec/template/common/contract/contract.json.

package contract

// SchemaVersion is the JSON output schema version every envelope carries.
const SchemaVersion = "1.0"

// CodeSpec is the canonical exit code + retryability for an E_* error code.
type CodeSpec struct {
	Exit      int
	Retryable bool
	Core      bool
}

// Codes is the frozen canonical error-code table (core + this tool's registered
// extensions). It is the binding source for code -> exit -> retryable.
var Codes = map[string]CodeSpec{
	"E_INTEGRITY":             {Exit: 1, Retryable: false, Core: true},
	"E_IO":                    {Exit: 1, Retryable: false, Core: true},
	"E_UNKNOWN":               {Exit: 1, Retryable: false, Core: true},
	"E_USAGE":                 {Exit: 2, Retryable: false, Core: true},
	"E_VALIDATION":            {Exit: 2, Retryable: false, Core: true},
	"E_NOT_FOUND":             {Exit: 3, Retryable: false, Core: true},
	"E_AUTH":                  {Exit: 4, Retryable: false, Core: true},
	"E_CONFIG":                {Exit: 4, Retryable: false, Core: true},
	"E_FORBIDDEN":             {Exit: 4, Retryable: false, Core: true},
	"E_CONFIRMATION_REQUIRED": {Exit: 5, Retryable: false, Core: true},
	"E_CONFLICT":              {Exit: 6, Retryable: false, Core: true},
	"E_NETWORK":               {Exit: 7, Retryable: true, Core: true},
	"E_RATE_LIMITED":          {Exit: 7, Retryable: true, Core: true},
	"E_SERVER":                {Exit: 7, Retryable: true, Core: true},
	"E_TIMEOUT":               {Exit: 8, Retryable: true, Core: true},
	"E_INTERRUPTED":           {Exit: 130, Retryable: true, Core: true},
}

// ExitFor returns the canonical process exit code for an E_* code (1 if unknown).
func ExitFor(code string) int {
	if s, ok := Codes[code]; ok {
		return s.Exit
	}
	return 1
}

// Retryable reports whether an agent may back off and retry an E_* code.
func Retryable(code string) bool {
	return Codes[code].Retryable
}

// Canonical envelope key sets (snake_case).
var SuccessEnvelopeKeys = []string{"ok", "schema_version", "data", "meta"}
var ErrorEnvelopeKeys = []string{"ok", "schema_version", "error", "meta"}
var ErrorObjectKeys = []string{"code", "message", "details", "retryable"}
var MetaRequiredKeys = []string{"duration_ms"}
var MetaOptionalKeys = []string{"notices"}
